#This is a extended version of https://github.com/osixia/docker-keepalived/blob/master/image/Dockerfile

FROM osixia/keepalived:latest

# Download, build and install Keepalived
RUN apk --no-cache add \
    tcpdump \
    ip6tables

